echo "DETAIL INSTALASI DEFAULT"
echo "==============================================="
echo "" 
echo "Service" 
echo "-------"  
echo "OpenVPN  : TCP 1194 (client config : http://[IP]:81/client.ovpn)"  
echo "OpenSSH  : 22, 143"  
echo "Dropbear : 80, 109, 110, 3128"  
echo "SSL Port : 443"
echo "Squid3   : 8000, 8080 (limit to IP SSH)"  
echo "badvpn   : badvpn-udpgw port 7300"  
echo "nginx    : 81"  
echo ""  
echo "Tools"  
echo "-----" 
echo "axel"
echo "bmon"
echo "htop"
echo "iftop"
echo "mtr"
echo "rkhunter"
echo "nethogs: nethogs venet0"
echo "" 
echo "Script"  
echo "------" 
echo "Premium Script telah terinstall pada server Anda!" 
echo "Ketik ${red}menu${NC} untuk menampilkan menu dari premium script."
echo "Penjelasan dari kegunaan premium script dapat dilihat di website"  
echo ""  
echo "Fitur lain" 
echo "----------"  
echo "Webmin   : http://[IP]:10000/"  
echo "vnstat   : http://[IP]:81/vnstat/"  
echo "MRTG     : http://[IP]:81/mrtg/"  
echo "Timezone : Asia/Jakarta"  
echo "Fail2Ban : [on]"  
echo "IPv6     : [off]"  
echo "" 
echo "==============================================="  
